
from enum import Enum
from dataclasses import dataclass


_deolingo_prefix = "_deolingo_"


def prefix(atom):
    """
    Returns a string representing the prefix for the atoms generated by deolingo.
    """
    return _deolingo_prefix + atom


def unprefix(atom):
    """
    Returns the atom without the prefix '_deolingo_'.
    """
    return atom[len(_deolingo_prefix):]


@dataclass
class DeonticAtom:

    name: str
    long_name: str

    def prefixed(self):
        return prefix(self.name)

    def prefixed_long_name(self):
        return prefix(self.long_name)

    def wrap(self, atom):
        return f"{self.prefixed()}({atom})"


class DeonticAtoms(Enum):
    """
    Enumeration of the deontic atoms.
    """
    OBLIGATORY = DeonticAtom("ob", "obligatory")
    FORBIDDEN = DeonticAtom("fb", "forbidden")
    OMISSIBLE = DeonticAtom("om", "omissible")
    PERMITTED = DeonticAtom("pm", "permitted")
    OPTIONAL = DeonticAtom("op", "optional")
    PERMITTED_BY_DEFAULT = DeonticAtom("pm_def", "permitted_by_default")
    HOLDS = DeonticAtom("holds", "holds")
    DEONTIC = DeonticAtom("deontic", "deontic")
    PERMITTED_IMPLICITLY = DeonticAtom("pm_imp", "permitted_implicitly")
    VIOLATED = DeonticAtom("viol", "violated")
    FULFILLED = DeonticAtom("ful", "fulfilled")
    VIOLATED_OBLIGATION = DeonticAtom("ob_viol", "violated_obligation")
    FULFILLED_OBLIGATION = DeonticAtom("ob_ful", "fulfilled_obligation")
    NON_VIOLATED_OBLIGATION = DeonticAtom("ob_not_viol", "non_violated_obligation")
    NON_FULFILLED_OBLIGATION = DeonticAtom("ob_not_ful", "non_fulfilled_obligation")
    UNDETERMINED_OBLIGATION = DeonticAtom("ob_und", "undetermined_obligation")
    DEFAULT_OBLIGATION = DeonticAtom("ob_def", "default_obligation")
    VIOLATED_PROHIBITION = DeonticAtom("fb_viol", "violated_prohibition")
    FULFILLED_PROHIBITION = DeonticAtom("fb_ful", "fulfilled_prohibition")
    NON_VIOLATED_PROHIBITION = DeonticAtom("fb_not_viol", "non_violated_prohibition")
    NON_FULFILLED_PROHIBITION = DeonticAtom("fb_not_ful", "non_fulfilled_prohibition")
    UNDETERMINED_PROHIBITION = DeonticAtom("fb_und", "undetermined_prohibition")
    DEFAULT_PROHIBITION = DeonticAtom("fb_def", "default_prohibition")

    @classmethod
    def get_all(cls):
        return [atom for atom in DeonticAtoms]

    @classmethod
    def get_all_names(cls):
        return [atom.value.name for atom in cls.get_all()]

    @classmethod
    def with_name(cls, name):
        for atom in cls.get_all():
            if atom.value.name == name:
                return atom
        return None

    @classmethod
    def with_prefixed_name(cls, name):
        for atom in cls.get_all():
            if atom.value.prefixed() == name:
                return atom
        return None


def deontic(deontic_atom):
    return DeonticAtoms.DEONTIC.value.wrap(deontic_atom)


def violated(deontic_atom):
    return DeonticAtoms.VIOLATED.value.wrap(deontic_atom)


def fulfilled(deontic_atom):
    return DeonticAtoms.FULFILLED.value.wrap(deontic_atom)


def obligatory(deontic_atom):
    return DeonticAtoms.OBLIGATORY.value.wrap(deontic_atom)


def forbidden(deontic_atom):
    return DeonticAtoms.FORBIDDEN.value.wrap(deontic_atom)


def optional(deontic_atom):
    return DeonticAtoms.OPTIONAL.value.wrap(deontic_atom)


def holds(deontic_atom):
    return DeonticAtoms.HOLDS.value.wrap(deontic_atom)


def permitted_implicitly(deontic_atom):
    return DeonticAtoms.PERMITTED_IMPLICITLY.value.wrap(deontic_atom)


def omissible(deontic_atom):
    return DeonticAtoms.OMISSIBLE.value.wrap(deontic_atom)


def permitted(deontic_atom):
    return DeonticAtoms.PERMITTED.value.wrap(deontic_atom)


def permitted_by_default(deontic_atom):
    return DeonticAtoms.PERMITTED_BY_DEFAULT.value.wrap(deontic_atom)


def violated_obligation(deontic_atom):
    return DeonticAtoms.VIOLATED_OBLIGATION.value.wrap(deontic_atom)


def fulfilled_obligation(deontic_atom):
    return DeonticAtoms.FULFILLED_OBLIGATION.value.wrap(deontic_atom)


def non_violated_obligation(deontic_atom):
    return DeonticAtoms.NON_VIOLATED_OBLIGATION.value.wrap(deontic_atom)


def non_fulfilled_obligation(deontic_atom):
    return DeonticAtoms.NON_FULFILLED_OBLIGATION.value.wrap(deontic_atom)


def undetermined_obligation(deontic_atom):
    return DeonticAtoms.UNDETERMINED_OBLIGATION.value.wrap(deontic_atom)


def default_obligation(deontic_atom):
    return DeonticAtoms.DEFAULT_OBLIGATION.value.wrap(deontic_atom)


def violated_prohibition(deontic_atom):
    return DeonticAtoms.VIOLATED_PROHIBITION.value.wrap(deontic_atom)


def fulfilled_prohibition(deontic_atom):
    return DeonticAtoms.FULFILLED_PROHIBITION.value.wrap(deontic_atom)


def non_violated_prohibition(deontic_atom):
    return DeonticAtoms.NON_VIOLATED_PROHIBITION.value.wrap(deontic_atom)


def non_fulfilled_prohibition(deontic_atom):
    return DeonticAtoms.NON_FULFILLED_PROHIBITION.value.wrap(deontic_atom)


def undetermined_prohibition(deontic_atom):
    return DeonticAtoms.UNDETERMINED_PROHIBITION.value.wrap(deontic_atom)


def default_prohibition(deontic_atom):
    return DeonticAtoms.DEFAULT_PROHIBITION.value.wrap(deontic_atom)
